version: '3.7'

services:
    app:
        container_name: pizza_app
        build:
            context: .
            target: development
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '0.0.0.0:${HOST_PORT}:${HOST_PORT}'
        command: npm run start:dev
        env_file:
            - .env
        depends_on:
            - postgres
    postgres:
        container_name: pizza_postgres
        image: postgres:13.1-alpine
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_LOGIN}
            POSTGRES_DB: ${POSTGRES_DATABASE}
            PG_DATA: /var/lib/postgresql/data
        ports:
            - '0.0.0.0:${POSTGRES_PORT}:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
    pgadmin:
        container_name: pizza_pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PA_LOGIN}
            PGADMIN_DEFAULT_PASSWORD: ${PA_PASSWORD}
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        ports:
            - '0.0.0.0:${PA_PORT}:80'
        depends_on:
            - postgres
networks:
    back:
volumes:
    pgdata:
    pgadmin-data:
